services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kuyumcu_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:////app/data/kuyumculuk.db
      - MASTER_PASSWORD_HASH=pbkdf2_sha256$600000$ec730e443f19395909ed35b54ae5bc0c$fc198c67066318bb7b40679ec8575eede32e68801f9745f96823a174db463308
    deploy:
      resources:
        limits:
          memory: 250M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://63.181.78.45:8000
    container_name: kuyumcu_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://63.181.78.45:8000
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 400M
